export const siteConfig = {
  name: 'Engineer Ahmad Raza',
  title: 'Mechatronics Engineer & Automation Specialist',
  tagline: 'Building the Future with Intelligent Systems',
  email: 'ahmadrazas172001@gmail.com',
  phone: '+923453469979',
  location: 'Sargodha District, Punjab, Pakistan',
  linkedin: 'https://www.linkedin.com/in/engineerahmadraza',
  upwork: 'https://www.upwork.com/freelancers/~01b0e16f3156c649be',
  fiverr: 'https://www.fiverr.com/users/engr_ahmadraza',
  facebook: 'https://www.facebook.com/profile.php?id=61560479939595',
  freelancer: 'https://www.freelancer.com/u/engr305',
  github: 'https://github.com/engineerahmadraza',
};

export const stats = [
  { label: 'Projects Completed', value: '50+', suffix: '' },
  { label: 'Client Satisfaction', value: '99', suffix: '%' },
  { label: 'Years Experience', value: '3', suffix: '+' },
  { label: 'Countries Served', value: '15', suffix: '+' },
];

export const skills = [
  {
    category: 'Engineering Design',
    icon: '⚙️',
    items: [
      { name: 'SolidWorks', level: 90 },
      { name: 'AutoCAD', level: 88 },
      { name: 'MATLAB / Simulink', level: 85 },
      { name: 'Abaqus FEA', level: 75 },
      { name: 'CNC Machining', level: 78 },
    ],
  },
  {
    category: 'Embedded & IoT',
    icon: '🤖',
    items: [
      { name: 'Arduino / ESP32', level: 95 },
      { name: 'PIC18 Microcontroller', level: 88 },
      { name: 'Tiva C Series', level: 82 },
      { name: 'Blynk IoT Platform', level: 85 },
      { name: 'PLC / HMI Systems', level: 80 },
    ],
  },
  {
    category: 'AI / ML & Software',
    icon: '🧠',
    items: [
      { name: 'Python (AI/ML/DL)', level: 88 },
      { name: 'TensorFlow / PyTorch', level: 80 },
      { name: 'MATLAB AI Toolbox', level: 82 },
      { name: 'C / C++', level: 85 },
      { name: 'C# / .NET', level: 78 },
    ],
  },
  {
    category: 'Industrial Systems',
    icon: '🏭',
    items: [
      { name: 'KHS / Sidel / Krones', level: 85 },
      { name: 'Tetra Pak Systems', level: 82 },
      { name: 'Pneumatics (MAC Valves)', level: 88 },
      { name: 'Compressed Air Networks', level: 85 },
      { name: 'Beverage Line Automation', level: 83 },
    ],
  },
];

export const experience = [
  {
    company: 'Projexon Engineering Solutions',
    role: 'Mechatronics Engineer',
    period: 'Aug 2025 – Present',
    duration: '10 months',
    location: 'Lahore, Punjab, Pakistan',
    type: 'full-time',
    color: '#c62828',
    description: 'Leading FMCG and industrial automation projects. Specialized in beverage line expertise (KHS, Sidel, Krones, Tetra Pak), compressed air network studies, PLC/HMI retrofits, and AC→DC conversions. Ensuring safe, efficient, and compliant engineering solutions for major industrial clients.',
    highlights: [
      'Beverage line automation (KHS, Sidel, Krones, Tetra Pak)',
      'Compressed air network studies & dust collector integration',
      'PLC/HMI retrofits and system upgradation',
      'Safety system design and compliance',
    ],
  },
  {
    company: 'Fiverr',
    role: 'Freelance Mechatronics Consultant',
    period: 'Jan 2023 – Present',
    duration: '3+ years',
    location: 'Remote – Global',
    type: 'freelance',
    color: '#1dbf73',
    description: 'Top-rated freelancer providing consultancy in Mechatronics Engineering. Specialized in robotics, kinematics, dynamics, control systems, MATLAB simulations, Python AI/ML/DL models, and automated system designs for academic and industrial clients globally.',
    highlights: [
      'MATLAB-based robotics simulations & kinematics analysis',
      'Python AI/ML/DL model development',
      'SolidWorks & AutoCAD design services',
      'Arduino & Simulink control logic implementation',
    ],
  },
  {
    company: 'Daira Engineering',
    role: 'Robotics Engineer',
    period: 'Jul 2024 – Sep 2024',
    duration: '3 months',
    location: 'Johar Town, Lahore, Pakistan',
    type: 'contract',
    color: '#ffb300',
    description: 'Designed assemblies and engineering layouts using SolidWorks. Led 3D printing and custom part fabrication for robotic systems. Supported PLC programming and industrial automation projects from concept to testing.',
    highlights: [
      'SolidWorks 3D assembly design & schematics',
      '3D printing & custom robotic part fabrication',
      'PLC programming & system testing',
      'Industrial automation project support',
    ],
  },
  {
    company: 'Sun Power Pakistan',
    role: 'Sustainable Energy Systems Engineer',
    period: 'Jun 2024 – Jul 2024',
    duration: '2 months',
    location: 'Lahore District, Pakistan',
    type: 'internship',
    color: '#f9a825',
    description: 'Gained hands-on experience in assembling and deploying solar panel systems. Contributed to sustainable energy practices and renewable energy installation projects across Pakistan.',
    highlights: [
      'Solar panel assembly & deployment',
      'Sustainable energy system design',
      'Renewable energy practices & compliance',
    ],
  },
  {
    company: 'PCSIR (Pakistan Council of Scientific & Industrial Research)',
    role: 'Electro Mechanical Engineer',
    period: 'Jul 2023 – Sep 2023',
    duration: '3 months',
    location: 'Lahore, Punjab, Pakistan',
    type: 'internship',
    color: '#00bcd4',
    description: 'Performed quality control tests on mechanical and electrical components. Ensured ISO-compliant evaluation of industrial samples achieving 99.5% accuracy. Collaborated with R&D and production teams to troubleshoot complex system faults.',
    highlights: [
      '99.5% accuracy in ISO-compliant quality testing',
      'Mechanical & electrical component evaluation',
      'R&D collaboration & fault troubleshooting',
    ],
  },
];

export const defaultProjects = [
  {
    id: '1',
    title: 'Automatic Stamping Machine (IoT)',
    category: 'Embedded Systems',
    tags: ['IoT', 'Blynk', 'Arduino', 'Automation'],
    description: 'Designed and developed an Automatic Stamping Machine controlled via Blynk IoT platform. Significantly reduced production costs by 40% and improved manufacturing efficiency through real-time remote monitoring and control.',
    image: '/projects/stamping-machine.jpg',
    link: 'https://www.fiverr.com/users/engr_ahmadraza',
    featured: true,
    color: '#c62828',
  },
  {
    id: '2',
    title: 'Automatic Coffee Machine (PIC18)',
    category: 'Microcontroller',
    tags: ['PIC18', 'Embedded C', 'Automation', 'IoT'],
    description: 'Engineered a fully automated coffee machine controlled by PIC18 microcontroller. Enhanced user experience through precise timing automation, multiple drink presets, and sensor-based ingredient management.',
    image: '/projects/coffee-machine.jpg',
    link: 'https://www.fiverr.com/users/engr_ahmadraza',
    featured: true,
    color: '#6d4c41',
  },
  {
    id: '3',
    title: 'Automatic Radar System',
    category: 'Robotics & Sensing',
    tags: ['Arduino', 'MATLAB', 'Ultrasonic', 'Servo'],
    description: 'Implemented a real-time object detection radar system using Arduino and MATLAB visualization. Improved detection accuracy to 95% with 360° sweep capability and distance mapping on MATLAB GUI.',
    image: '/projects/radar-system.jpg',
    link: 'https://www.fiverr.com/users/engr_ahmadraza',
    featured: true,
    color: '#00838f',
  },
  {
    id: '4',
    title: 'Dynamic Pizza Ordering System',
    category: 'Software Development',
    tags: ['C#', 'SQL Server', 'WinForms', 'Database'],
    description: 'Created a full-featured pizza ordering management system using C# and SQL Server. Streamlined the order process, integrated real-time inventory tracking, and boosted customer satisfaction with an intuitive UI.',
    image: '/projects/pizza-system.jpg',
    link: 'https://www.fiverr.com/users/engr_ahmadraza',
    featured: false,
    color: '#e65100',
  },
  {
    id: '5',
    title: 'MATLAB Robot Kinematics Solver',
    category: 'AI & Simulation',
    tags: ['MATLAB', 'Robotics', 'Kinematics', 'Simulation'],
    description: 'Developed a comprehensive robot kinematics solver in MATLAB for forward and inverse kinematics analysis. Used by academic researchers and industry engineers for 6-DOF robot arm trajectory planning.',
    image: '/projects/kinematics.jpg',
    link: 'https://www.upwork.com/freelancers/~01b0e16f3156c649be',
    featured: false,
    color: '#0077b5',
  },
  {
    id: '6',
    title: 'PLC-Based Conveyor System',
    category: 'Industrial Automation',
    tags: ['PLC', 'HMI', 'SCADA', 'Automation'],
    description: 'Designed and programmed a PLC-based conveyor automation system for FMCG manufacturing. Implemented HMI touchscreen interface, fault detection, and real-time process monitoring for enhanced production efficiency.',
    image: '/projects/plc-conveyor.jpg',
    link: 'https://www.linkedin.com/in/engineerahmadraza',
    featured: false,
    color: '#1565c0',
  },
  {
    id: '7',
    title: 'AI-Based Predictive Maintenance',
    category: 'AI & ML',
    tags: ['Python', 'Machine Learning', 'TensorFlow', 'IoT'],
    description: 'Built a machine learning model for predictive maintenance of industrial equipment using sensor data. Achieved 92% accuracy in fault prediction, reducing downtime by 35% for manufacturing clients.',
    image: '/projects/predictive-maintenance.jpg',
    link: 'https://www.upwork.com/freelancers/~01b0e16f3156c649be',
    featured: true,
    color: '#6a1b9a',
  },
  {
    id: '8',
    title: 'Solar Energy Monitoring Dashboard',
    category: 'Sustainable Energy',
    tags: ['IoT', 'ESP32', 'Solar', 'Dashboard'],
    description: 'Created a real-time solar energy monitoring system using ESP32 and cloud dashboard. Tracks voltage, current, power output, and efficiency metrics for residential and commercial solar installations.',
    image: '/projects/solar-dashboard.jpg',
    link: 'https://www.fiverr.com/users/engr_ahmadraza',
    featured: false,
    color: '#f9a825',
  },
];

export const researchPapers = [
  {
    id: '1',
    title: 'Optimization of Pneumatic Control Systems in High-Speed Beverage Filling Lines',
    journal: 'International Journal of Industrial Automation',
    year: '2024',
    abstract: 'This paper presents a novel approach to optimizing MAC valve configurations in KHS and Krones beverage filling lines, achieving 23% reduction in air consumption while maintaining fill accuracy to ±0.5ml.',
    tags: ['Pneumatics', 'FMCG', 'Optimization', 'Beverage'],
    status: 'Published (Client)',
    color: '#c62828',
  },
  {
    id: '2',
    title: 'Deep Learning Approaches for Real-Time Fault Detection in Rotary Machinery',
    journal: 'IEEE Transactions on Industrial Electronics',
    year: '2024',
    abstract: 'Proposes a CNN-LSTM hybrid architecture for vibration-based fault detection in industrial rotary machinery. Achieved 94.7% classification accuracy on experimental datasets with sub-100ms inference time.',
    tags: ['Deep Learning', 'Fault Detection', 'CNN-LSTM', 'Vibration'],
    status: 'Published (Client)',
    color: '#6a1b9a',
  },
  {
    id: '3',
    title: 'Comparative Analysis of PID vs Model Predictive Control for Robotic Arm Trajectory Planning',
    journal: 'Robotics and Autonomous Systems Journal',
    year: '2023',
    abstract: 'A systematic comparison of classical PID and MPC controllers for 6-DOF robotic arm applications. MPC demonstrated 31% improvement in trajectory accuracy and 18% reduction in energy consumption.',
    tags: ['Robotics', 'MPC', 'PID', 'Control Systems'],
    status: 'Published (Client)',
    color: '#00838f',
  },
  {
    id: '4',
    title: 'IoT-Enabled Smart Manufacturing: A Framework for Small-Scale Industries in Pakistan',
    journal: 'Journal of Manufacturing Technology Management',
    year: '2023',
    abstract: 'Presents an accessible IoT implementation framework tailored for SME manufacturers in developing economies. Case studies demonstrate 28% productivity improvement with minimal capital investment.',
    tags: ['IoT', 'Smart Manufacturing', 'Industry 4.0', 'SME'],
    status: 'Published (Client)',
    color: '#1565c0',
  },
];

export const categories = ['All', 'Embedded Systems', 'AI & ML', 'Industrial Automation', 'Robotics & Sensing', 'Software Development', 'Microcontroller', 'Sustainable Energy'];
